# this Dockerfile is used by scripts/build-dll
ARG DIGEST
FROM mcr.microsoft.com/dotnet/framework/sdk@${DIGEST} as csharp-build-env
WORKDIR /app
COPY ./src/* ./

# The resulting dll is '/app/bin/Debug/RanchergMSACredentialProvider.dll'
RUN dotnet build
