FROM registry.suse.com/bci/golang:1.25.9

ARG ARCH
ENV ARCH=${ARCH}

RUN zypper -n install git docker vim less file curl wget patch
RUN if [ "${ARCH}" == "amd64" ]; then \
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2; \
    fi

RUN zypper --non-interactive install tar python3 python3-pip

# Install YAMLLint for Hull
ARG yamllint_version=1.26.3
LABEL yamllint_version=$yamllint_version
RUN pip install "yamllint==$yamllint_version"

WORKDIR /source

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
