{{- if .Values.credential.enabled -}}
apiVersion: windows.k8s.io/v1
kind: GMSACredentialSpec
metadata:
  name: {{ lower .Values.credential.domainJoinConfig.machineAccountName | replace "_" "-" }}  #This is an arbitrary name but it will be used as a reference
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
credspec:
  ActiveDirectoryConfig:
    GroupManagedServiceAccounts:
      - Name: {{ .Values.credential.domainJoinConfig.machineAccountName }} # Username of the GMSA account
        Scope: {{ .Values.credential.domainJoinConfig.netBiosName }} # NETBIOS Domain Name
      - Name: {{ .Values.credential.domainJoinConfig.machineAccountName }} # Username of the GMSA account
        Scope: {{ .Values.credential.domainJoinConfig.dnsName }} # DNS Domain Name
{{- if .Values.credential.hostAccountConfig }}
    HostAccountConfig:
      PortableCcgVersion: {{ required "credential.hostAccountConfig.portableCCGVersion must be provided if credential.hostAccountConfig is set" .Values.credential.hostAccountConfig.portableCcgVersion | quote }} # This needs to equal the current version of CCG which right now is '1'
      PluginGUID:   {{ printf "{%s}" (required "credential.hostAccountConfig.pluginGUID must be provided if credential.hostAccountConfig is set" .Values.credential.hostAccountConfig.pluginGUID) | quote }} # CCG Plugin GUID
      PluginInput: {{ required "credential.hostAccountConfig.pluginInput must be provided if credential.hostAccountConfig is set" .Values.credential.hostAccountConfig.pluginInput | quote }} # Format of this field is dependent upon specific CCG Plugin
{{- end }}
  CmsPlugins:
    - ActiveDirectory
  DomainJoinConfig:
    DnsName: {{ .Values.credential.domainJoinConfig.dnsName }} # DNS Domain Name
    DnsTreeName:  {{ .Values.credential.domainJoinConfig.dnsTreeName }} # DNS Domain Name Root
    Guid:  {{ .Values.credential.domainJoinConfig.guid }} # GUID of Domain
    MachineAccountName:  {{ .Values.credential.domainJoinConfig.machineAccountName }} # Username of the GMSA account
    NetBiosName:  {{ .Values.credential.domainJoinConfig.netBiosName }} # NETBIOS Domain Name
    Sid:  {{ .Values.credential.domainJoinConfig.sid }} # SID of Domain
{{- end -}}
