{{- $namespaces := dict "_0" (include "rancher-gmsa-plugin-installer.namespace" .) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rancher-gmsa-plugin-installer.name" . }}-patch-sa
  namespace: {{ template "rancher-gmsa-plugin-installer.namespace" . }}
  labels:
    app: {{ template "rancher-gmsa-plugin-installer.name" . }}-patch-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: {{ template "rancher-gmsa-plugin-installer.name" . }}-patch-sa
      labels:
        app: {{ template "rancher-gmsa-plugin-installer.name" . }}-patch-sa
    spec:
      serviceAccountName: {{ template "rancher-gmsa-plugin-installer.name" . }}-patch-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      restartPolicy: Never
      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
      containers:
      {{- range $_, $ns := $namespaces }}
      - name: patch-sa-{{ $ns }}
        image: {{ template "system_default_registry" $ }}{{ $.Values.global.kubectl.repository }}:{{ $.Values.global.kubectl.tag }}
        imagePullPolicy: {{ $.Values.global.kubectl.pullPolicy }}
        command: ["kubectl", "patch", "serviceaccount", "default", "-p", "{\"automountServiceAccountToken\": false}"]
        args: ["-n", "{{ $ns }}"]
      {{- end }}
{{- range $_, $ns := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "rancher-gmsa-plugin-installer.name" $ }}-patch-sa
  namespace: {{ $ns }}
  labels:
    app: {{ template "rancher-gmsa-plugin-installer.name" $ }}-patch-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
    "helm.sh/hook-weight": "0"
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "rancher-gmsa-plugin-installer.name" $ }}-patch-sa
  namespace: {{ $ns }}
  labels:
    app: {{ template "rancher-gmsa-plugin-installer.name" $ }}-patch-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
    "helm.sh/hook-weight": "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "rancher-gmsa-plugin-installer.name" $ }}-patch-sa
subjects:
- kind: ServiceAccount
  name: {{ template "rancher-gmsa-plugin-installer.name" $ }}-patch-sa
  namespace: {{ template "rancher-gmsa-plugin-installer.namespace" $ }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rancher-gmsa-plugin-installer.name" . }}-patch-sa
  namespace: {{ template "rancher-gmsa-plugin-installer.namespace" . }}
  labels:
    app: {{ template "rancher-gmsa-plugin-installer.name" . }}-patch-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
    "helm.sh/hook-weight": "0"
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
{{- range $_, $ns := $namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "rancher-gmsa-plugin-installer.name" $ }}
  namespace: {{ $ns }}
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
