name: Pull Request CI

on:
  pull_request:
    paths-ignore:
      - '*.build'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'Makefile'

jobs:
  go-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
        with:
          args: --timeout=10m
          version: v1.64.7
      - name: go-format
        run: test -z "$(go fmt ./... | tee /dev/stderr)"

  charts-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: validate-charts
        run: ./scripts/validate-charts

  linux-tests:
    needs: [go-validation, charts-validation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: test-go
        run: ./scripts/test

  windows-tests:
    needs: [go-validation, charts-validation]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: test-go
        run: bash ./scripts/test

  chart-tests:
    needs: [go-validation, charts-validation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: test-charts
        run: ./scripts/test-charts

  build-all-binaries:
    needs: [linux-tests, windows-tests, chart-tests]
    runs-on: ubuntu-latest
    env:
      CROSS: true
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Build All Binaries
        run: bash ./scripts/build
      - name: Validate CI
        run: bash ./scripts/validate-ci

  build-windows-containers:
    needs: [linux-tests, windows-tests, chart-tests]
    runs-on: windows-2022
    env:
      REPO: ${{ vars.REPO }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: build-binaries
        run: bash ./scripts/build
      - name: build-containers
        run: bash ./scripts/package
